version: '3.4'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data/mongo:/data/db
    
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  currencyconversor.api:
    image: ${DOCKER_REGISTRY-}currencyconversorapi
    build:
      context: .
      dockerfile: CurrencyConversor/Dockerfile
